"""add_audit_tables

Create approval_request, audit_log (partitioned), mobile_action_log (PostGIS),
and report_number_sequence tables.

Revision ID: dcb529267be5
Revises: 6524ad295e93
Create Date: 2026-02-15 02:00:51.219037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dcb529267be5'
down_revision: Union[str, None] = '6524ad295e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── 1. approval_request ──────────────────────────────────────────
    op.create_table('approval_request',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('request_type', postgresql.ENUM(
            'new_policy', 'payment', 'cancellation', 'endorsement', 'other',
            name='approval_request_type', create_type=False
        ), nullable=False),
        sa.Column('status', postgresql.ENUM(
            'pending', 'approved', 'rejected',
            name='approval_status_type', create_type=False
        ), server_default=sa.text("'pending'::approval_status_type"), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('payload', postgresql.JSONB(), nullable=False),
        sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
        sa.Column('submitted_from_device_id', sa.Integer(), nullable=True),
        sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
        sa.Column('review_notes', sa.Text(), nullable=True),
        sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['submitted_by_user_id'], ['app_user.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['submitted_from_device_id'], ['device_session.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_approval_request_status', 'approval_request', ['status'])
    op.create_index('idx_approval_request_submitted_by', 'approval_request', ['submitted_by_user_id'])

    # ── 2. audit_log (partitioned by RANGE on changed_at) ───────────
    op.execute("""
        CREATE TABLE audit_log (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
            table_name  VARCHAR(63) NOT NULL,
            record_id   INTEGER     NOT NULL,
            action      VARCHAR(10) NOT NULL,
            old_values  JSONB,
            new_values  JSONB,
            changed_by_user_id INTEGER,
            changed_by  VARCHAR(100),
            changed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, changed_at)
        ) PARTITION BY RANGE (changed_at)
    """)
    op.create_index('idx_audit_log_table_record', 'audit_log', ['table_name', 'record_id'])
    op.create_index('idx_audit_log_changed_at', 'audit_log', ['changed_at'])

    # Create initial partition for 2026
    op.execute("""
        CREATE TABLE audit_log_2026 PARTITION OF audit_log
        FOR VALUES FROM ('2026-01-01') TO ('2027-01-01')
    """)

    # ── 3. mobile_action_log (with PostGIS geometry) ─────────────────
    op.create_table('mobile_action_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('device_session_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('action_type', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=True),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('request_payload', postgresql.JSONB(), nullable=True),
        sa.Column('response_status', sa.SmallInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['device_session_id'], ['device_session.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # Add geometry column separately using PostGIS function
    op.execute("""
        SELECT AddGeometryColumn('public', 'mobile_action_log', 'geom', 4326, 'POINT', 2)
    """)
    op.create_index('idx_mobile_action_log_user', 'mobile_action_log', ['user_id'])
    op.create_index('idx_mobile_action_log_device', 'mobile_action_log', ['device_session_id'])
    op.create_index('idx_mobile_action_log_created', 'mobile_action_log', ['created_at'])

    # ── 4. report_number_sequence ────────────────────────────────────
    op.create_table('report_number_sequence',
        sa.Column('prefix', sa.String(length=10), nullable=False),
        sa.Column('date_part', sa.String(length=8), nullable=False),
        sa.Column('last_number', sa.Integer(), server_default='0', nullable=False),
        sa.PrimaryKeyConstraint('prefix'),
        sa.UniqueConstraint('prefix', 'date_part', name='uq_report_seq'),
    )


def downgrade() -> None:
    op.drop_table('report_number_sequence')
    op.drop_table('mobile_action_log')
    op.execute('DROP TABLE IF EXISTS audit_log_2026')
    op.execute('DROP TABLE IF EXISTS audit_log')
    op.drop_index('idx_approval_request_submitted_by', table_name='approval_request')
    op.drop_index('idx_approval_request_status', table_name='approval_request')
    op.drop_table('approval_request')
